# docker-compose.yml
version: '3'

services:
  frontend:
    build:
      context: ./CalenAI-frontend
      dockerfile: ./deployment/dockerfile
    ports:
      - "80:80"
    networks:
      - webapp-network

  backend:
    build:
      context: ./CalenAI-backend
      dockerfile: ./deployment/dockerfile
    ports:
      - "5000:5000"
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge
